# Generated by Django 5.0.6 on 2024-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sitter_passport_remove_sitter_ppt_img_pd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='given_nm',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
