# Generated by Django 5.0.6 on 2024-05-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pd',
            name='sitter',
        ),
        migrations.AddField(
            model_name='sitter',
            name='pd',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pd'),
        ),
    ]
