# Generated by Django 5.0.6 on 2024-05-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pd_sitter_sitter_pd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pd',
            old_name='second_name',
            new_name='second_nm',
        ),
        migrations.RenameField(
            model_name='pd',
            old_name='sur_name',
            new_name='sur_nm',
        ),
    ]
